/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Victor
 */
public class Detalle extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Detalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listafactura = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        enviar_factura = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_stock = new javax.swing.JTable();
        añadir_articulo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CodigoArticulo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        NombreArticulo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        PrecioArticulo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CodArt = new javax.swing.JTextField();
        CodFac = new javax.swing.JLabel();
        eliminar_articulo = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        Clientes = new javax.swing.JButton();
        nomfac = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(490, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FACTURA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 220, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Facturar a:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 100, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Código factura:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 140, 29));

        listafactura.setBackground(new java.awt.Color(102, 0, 153));
        listafactura.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        listafactura.setForeground(new java.awt.Color(255, 255, 255));
        listafactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Código Artículo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listafactura);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 370, 160));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, -1, -1));

        enviar_factura.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        enviar_factura.setForeground(new java.awt.Color(255, 255, 255));
        enviar_factura.setText("Enviar");
        enviar_factura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 2, true));
        enviar_factura.setContentAreaFilled(false);
        jPanel1.add(enviar_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, -1, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 146, -1, -1));

        atras.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("Atrás");
        atras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 2, true));
        atras.setContentAreaFilled(false);
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        Tabla_stock.setBackground(new java.awt.Color(102, 0, 153));
        Tabla_stock.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Tabla_stock.setForeground(new java.awt.Color(255, 255, 255));
        Tabla_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Tabla_stock);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 387, 160));

        añadir_articulo.setBackground(new java.awt.Color(255, 255, 255));
        añadir_articulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow-145761_960_720 (1).png"))); // NOI18N
        añadir_articulo.setBorderPainted(false);
        añadir_articulo.setContentAreaFilled(false);
        añadir_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadir_articuloActionPerformed(evt);
            }
        });
        jPanel1.add(añadir_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cód. artículo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 120, -1));

        CodigoArticulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CodigoArticulo.setForeground(new java.awt.Color(255, 255, 255));
        CodigoArticulo.setText("     ");
        jPanel1.add(CodigoArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 190, 20));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nombre:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 80, 29));

        NombreArticulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        NombreArticulo.setForeground(new java.awt.Color(255, 255, 255));
        NombreArticulo.setText("    ");
        jPanel1.add(NombreArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 200, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Precio:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        PrecioArticulo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        PrecioArticulo.setText("    ");
        jPanel1.add(PrecioArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 160, 30));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("STOCK");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 150, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cód. artículo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 120, 30));

        CodArt.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jPanel1.add(CodArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 120, 30));

        CodFac.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CodFac.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(CodFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 230, 30));

        eliminar_articulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        eliminar_articulo.setForeground(new java.awt.Color(255, 255, 255));
        eliminar_articulo.setText("Eliminar");
        eliminar_articulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 2, true));
        eliminar_articulo.setContentAreaFilled(false);
        jPanel1.add(eliminar_articulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, -1, -1));

        Total.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Total.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 200, 30));

        Clientes.setBackground(new java.awt.Color(204, 0, 0));
        Clientes.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Clientes.setText("...");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        jPanel1.add(Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 25, -1));

        nomfac.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        nomfac.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(nomfac, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 180, 20));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondodetalle.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadir_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadir_articuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadir_articuloActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Clientes;
    public javax.swing.JTextField CodArt;
    public javax.swing.JLabel CodFac;
    public javax.swing.JLabel CodigoArticulo;
    public javax.swing.JLabel NombreArticulo;
    public javax.swing.JTextField PrecioArticulo;
    public javax.swing.JTable Tabla_stock;
    public javax.swing.JLabel Total;
    public javax.swing.JButton atras;
    public javax.swing.JButton añadir_articulo;
    public javax.swing.JButton eliminar_articulo;
    public javax.swing.JButton enviar_factura;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable listafactura;
    public static javax.swing.JLabel nomfac;
    // End of variables declaration//GEN-END:variables
}
